main:
  push:
    - stages:
        - name: sync to github
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/xrr2016/extensions.git
            auth_type: https
            username: xrr2016
            password: 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
